name: Deploy ARM Template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Validate ARM template
        run: |
          az deployment group validate --resource-group AZB8-RG --template-file ./azuredeploy.json

      - name: Deploy ARM template
        run: |
          az deployment group create --resource-group AZB8-RG --template-file ./azuredeploy.json
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
